version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: wmsdipl-postgres
    environment:
      POSTGRES_DB: wmsdipl
      POSTGRES_USER: wmsdipl
      POSTGRES_PASSWORD: wmsdipl
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wmsdipl"]
      interval: 10s
      timeout: 5s
      retries: 5

  # keycloak:
  #   image: quay.io/keycloak/keycloak:24.0.5
  #   command: start-dev
  #   environment:
  #     KEYCLOAK_ADMIN: admin
  #     KEYCLOAK_ADMIN_PASSWORD: admin
  #   ports:
  #     - "8081:8080"
  #   depends_on:
  #     - postgres

volumes:
  pgdata:
