spring:
  application:
    name: core-api
  datasource:
    url: ${WMS_DB_URL:jdbc:postgresql://localhost:55432/wmsdipl}
    username: ${WMS_DB_USER:wmsdipl}
    password: ${WMS_DB_PASSWORD:wmsdipl}
  jpa:
    hibernate:
      ddl-auto: none  # Временно отключена валидация, т.к. схема создается через init_schema.sql
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false  # Миграции отключены - используем database/init_schema.sql

server:
  port: ${WMS_CORE_API_PORT:8080}

logging:
  level:
    root: INFO
    com.wmsdipl.core: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
